repo: https://charts.rook.io/release
chart: rook-ceph
icon: prometheus-logo.svg
latestImages:
  - name: crds.upgradeJob.image.busybox.registry/crds.upgradeJob.image.busybox.repository
    tag: crds.upgradeJob.image.busybox.tag
values:
  crds:
    upgradeJob:
      image:
        busybox:
          registry: olcne
          repository: kubectl
        kubectl:
          registry: olcne
          repository: kubectl
  alertmanager:
    alertmanagerSpec:
      image:
        registry: olcne
        repository: alertmanager
  prometheus:
    prometheusSpec:
      image:
        registry: olcne
        repository: prometheus
  prometheusOperator:
    admissionWebhooks:
      deployment:
        image:
          registry: olcne
          repository: prometheus-admission-webhook
          tag: "v0.85.0"
      patch:
        image:
          registry: olcne
          repository: kube-webhook-certgen
          tag: v1.13.1
    image:
      registry: olcne
      repository: prometheus-operator
      tag: "v0.85.0"
    prometheusConfigReloader:
      image:
        registry: olcne
        repository: prometheus-config-reloader
        tag: "v0.85.0"
    thanosImage:
      registry: olcne
      repository: thanos
  thanosRuler:
    thanosRulerSpec:
      image:
        registry: olcne
        repository: thanos

extraImages:
  deployment.yaml:
    - "{{ .Values.csi.cephcsi.repository }}:{{ .Values.csi.cephcsi.tag }}"
    - "{{ .Values.csi.registrar.repository }}:{{ .Values.csi.registrar.tag }}"
    - "{{ .Values.csi.provisioner.repository }}:{{ .Values.csi.provisioner.tag }}"
    - "{{ .Values.csi.snapshotter.repository }}:{{ .Values.csi.snapshotter.tag }}"
    - "{{ .Values.csi.attacher.repository }}:{{ .Values.csi.attacher.tag }}"
    - "{{ .Values.csi.resizer.repository }}:{{ .Values.csi.resizer.tag }}"
    - "{{ .Values.image.repository }}:{{ .Values.image.cephTag }}"

extraChartYqs:
  - '(.dependencies[] | select(.name == "library") | .repository) = "file://./charts/library"'
