repo: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
chartVersion: 77.6.0
icon: prometheus-logo.svg

latestImages:
  - name: .crds.upgradeJob.image.busybox | (.registry) + "/" + (.repository)
    tag: .crds.upgradeJob.image.busybox.tag
  - name: .crds.upgradeJob.image.kubectl | (.registry) + "/" + (.repository)
    tag: .crds.upgradeJob.image.kubectl.tag
  - name: .alertmanager.alertmanagerSpec.image | (.registry) + "/" + (.repository)
    tag: .alertmanager.alertmanagerSpec.image.tag
  - name: .prometheus.prometheusSpec.image | (.registry) + "/" + (.repository)
    tag: .prometheus.prometheusSpec.image.tag
  - name: .prometheusOperator.image | (.registry) + "/" + (.repository)
    tag: .prometheusOperator.image.tag
  - name: .prometheusOperator.admissionWebhooks.deployment.image | (.registry) + "/" + (.repository)
    tag: .prometheusOperator.admissionWebhooks.deployment.image.tag
  - name: .prometheusOperator.admissionWebhooks.patch.image | (.registry) + "/" + (.repository)
    tag: .prometheusOperator.admissionWebhooks.patch.image.tag
  - name: .prometheusOperator.prometheusConfigReloader.image | (.registry) + "/" + (.repository)
    tag: .prometheusOperator.prometheusConfigReloader.image.tag
  - name: .prometheusOperator.thanosImage | (.registry) + "/" + (.repository)
    tag: .prometheusOperator.thanosImage.tag
  - name: .thanosRuler.thanosRulerSpec.image | (.registry) + "/" + (.repository)
    tag: .thanosRuler.thanosRulerSpec.image.tag

values:
  grafana:
    enabled: false
  crds:
    upgradeJob:
      enabled: true
      forceConflicts: true
      image:
        busybox:
          registry: olcne
          repository: kubectl
        kubectl:
          registry: olcne
          repository: kubectl
  alertmanager:
    alertmanagerSpec:
      image:
        registry: olcne
        repository: alertmanager
  prometheus:
    prometheusSpec:
      image:
        registry: olcne
        repository: prometheus
  prometheusOperator:
    admissionWebhooks:
      deployment:
        image:
          registry: olcne
          repository: prometheus-admission-webhook
      patch:
        image:
          registry: olcne
          repository: kube-webhook-certgen
    image:
      registry: olcne
      repository: prometheus-operator
    prometheusConfigReloader:
      image:
        registry: olcne
        repository: prometheus-config-reloader
    thanosImage:
      registry: olcne
      repository: thanos
  thanosRuler:
    thanosRulerSpec:
      image:
        registry: olcne
        repository: thanos

transforms:
  "prometheus/prometheus.yaml":
    prepend: |
      {{- if .Values.prometheus.prometheusSpec.image }}
        {{- $registry := .Values.global.imageRegistry | default .Values.prometheus.prometheusSpec.image.registry -}}
        {{- if and .Values.prometheus.prometheusSpec.image.tag .Values.prometheus.prometheusSpec.image.sha }}
      # extra-image: {{ $registry }}/{{ .Values.prometheus.prometheusSpec.image.repository }}:{{ .Values.prometheus.prometheusSpec.image.tag }}@sha256:{{ .Values.prometheus.prometheusSpec.image.sha }}
        {{- else if .Values.prometheus.prometheusSpec.image.sha }}
      # extra-image: {{ $registry }}/{{ .Values.prometheus.prometheusSpec.image.repository }}@sha256:{{ .Values.prometheus.prometheusSpec.image.sha }}
        {{- else if .Values.prometheus.prometheusSpec.image.tag }}
      # extra-image: {{ $registry }}/{{ .Values.prometheus.prometheusSpec.image.repository }}:{{ .Values.prometheus.prometheusSpec.image.tag }}
        {{- else }}
      # extra-image: {{ $registry }}/{{ .Values.prometheus.prometheusSpec.image.repository }}
        {{- end }}
      {{- end }}
  "alertmanager/alertmanager.yaml":
    prepend: |
      {{- if .Values.alertmanager.alertmanagerSpec.image }}
        {{- $registry := .Values.global.imageRegistry | default .Values.alertmanager.alertmanagerSpec.image.registry -}}
        {{- if and .Values.alertmanager.alertmanagerSpec.image.tag .Values.alertmanager.alertmanagerSpec.image.sha }}
      # extra-image: {{ $registry }}/{{ .Values.alertmanager.alertmanagerSpec.image.repository }}:{{ .Values.alertmanager.alertmanagerSpec.image.tag }}@sha256:{{ .Values.alertmanager.alertmanagerSpec.image.sha }}
        {{- else if .Values.alertmanager.alertmanagerSpec.image.sha }}
      # extra-image: {{ $registry }}/{{ .Values.alertmanager.alertmanagerSpec.image.repository }}@sha256:{{ .Values.alertmanager.alertmanagerSpec.image.sha }}
        {{- else if .Values.alertmanager.alertmanagerSpec.image.tag }}
      # extra-image: {{ $registry }}/{{ .Values.alertmanager.alertmanagerSpec.image.repository }}:{{ .Values.alertmanager.alertmanagerSpec.image.tag }}
        {{- else }}
      # extra-image: {{ $registry }}/{{ .Values.alertmanager.alertmanagerSpec.image.repository }}
        {{- end }}
      {{- end }}
  "prometheus-operator/deployment.yaml":
    prepend: |
      {{- $configReloaderRegistry := .Values.global.imageRegistry | default .Values.prometheusOperator.prometheusConfigReloader.image.registry -}}
      {{- $thanosRegistry := .Values.global.imageRegistry | default .Values.prometheusOperator.thanosImage.registry -}}
      {{- if .Values.prometheusOperator.thanosImage.sha }}
      # extra-image: {{ $thanosRegistry }}/{{ .Values.prometheusOperator.thanosImage.repository }}:{{ .Values.prometheusOperator.thanosImage.tag }}@sha256:{{ .Values.prometheusOperator.thanosImage.sha }}
      {{- else }}
      # extra-image: {{ $thanosRegistry }}/{{ .Values.prometheusOperator.thanosImage.repository }}:{{ .Values.prometheusOperator.thanosImage.tag }}
      {{- end }}
      {{- if .Values.prometheusOperator.prometheusConfigReloader.image.sha }}
      # extra-image: {{ $configReloaderRegistry }}/{{ .Values.prometheusOperator.prometheusConfigReloader.image.repository }}:{{ .Values.prometheusOperator.prometheusConfigReloader.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.prometheusOperator.prometheusConfigReloader.image.sha }}
      {{- else }}
      # extra-image: {{ $configReloaderRegistry }}/{{ .Values.prometheusOperator.prometheusConfigReloader.image.repository }}:{{ .Values.prometheusOperator.prometheusConfigReloader.image.tag | default .Chart.AppVersion }}
      {{- end }}

extraChartYqs:
  - '(.dependencies[] | select(.name == "library") | .repository) = "file://./charts/library"'
