apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oci-capi.fullname" . }}-auth-config
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-oci
    clusterctl.cluster.x-k8s.io: ""
  {{- include "oci-capi.labels" . | nindent 4 }}
data:
  fingerprint: {{ required "authConfig.fingerprint is required" .Values.authConfig.fingerprint
    | b64enc | quote }}
  key: {{ required "authConfig.key is required" .Values.authConfig.key | b64enc |
    quote }}
  passphrase: {{ .Values.authConfig.passphrase | b64enc | quote }}
  region: {{ required "authConfig.region is required" .Values.authConfig.region |
    b64enc | quote }}
  tenancy: {{ required "authConfig.tenancy is required" .Values.authConfig.tenancy
    | b64enc | quote }}
  useInstancePrincipal: {{ required "authConfig.useInstancePrincipal is required"
    .Values.authConfig.useInstancePrincipal | b64enc | quote }}
  user: {{ required "authConfig.user is required" .Values.authConfig.user | b64enc
    | quote }}
type: Opaque
