apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oci-capi.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-oci
  {{- include "oci-capi.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
