apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    catalog.ocne.io/name: Oracle Cloud Native Environment Application Catalog
    catalog.ocne.io/protocol: helm
    catalog.ocne.io/displayName: {{ .Values.displayName }}
  labels:
    {{- include "app-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-catalog.selectorLabels" . | nindent 4 }}
