apiVersion: v2
appVersion: 0.6.0
description: A Helm chart to distribute the project ceph-csi-operator
name: ceph-csi-operator
type: application
version: 0.6.0
icon: icons/rook-logo.svg
kubeVersion: '>= 1.31.0 < 1.26.0'
