apiVersion: v2
name: grafana
# upstream version 7.3.0
version: 10.2.6
appVersion: 10.2.6
kubeVersion: '>= 1.26.0 < 1.34.0'
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.com
icon: icons/grafana-icon.svg
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana/helm-charts
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/grafana
maintainers:
  - name: zanhsieh
    email: zanhsieh@gmail.com
  - name: rtluckie
    email: rluckie@cisco.com
  - name: maorfr
    email: maor.friedman@redhat.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: torstenwalter
    email: mail@torstenwalter.de
type: application
keywords:
  - monitoring
  - metric
