apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "ovirt-csi-driver.fullname" . }}-ovirt.org
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/part-of: csi-driver-ovirt
  {{- include "ovirt-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: true
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent