apiVersion: v2
appVersion: 1.29.6
description: Helm chart for istio ztunnel components
icon: icons/android-192x192.png
keywords:
  - istio-ztunnel
  - istio
name: istio-ztunnel
sources:
  - https://github.com/istio/istio
version: 1.29.6
kubeVersion: '>= 1.31.0 < 1.36.0'
