apiVersion: v2
appVersion: 0.85.0
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
  and Prometheus rules combined with documentation and scripts to provide easy to
  operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus
  Operator.
home: https://github.com/prometheus-operator/kube-prometheus
icon: icons/prometheus-logo.svg
kubeVersion: ">= 1.26.0 < 1.33.0"
maintainers:
- email: andrew@quadcorps.co.uk
  name: andrewgkew
  url: https://github.com/andrewgkew
- email: gianrubio@gmail.com
  name: gianrubio
  url: https://github.com/gianrubio
- email: github.gkarthiks@gmail.com
  name: gkarthiks
  url: https://github.com/gkarthiks
- email: kube-prometheus-stack@sisti.pt
  name: GMartinez-Sisti
  url: https://github.com/GMartinez-Sisti
- email: github@jkroepke.de
  name: jkroepke
  url: https://github.com/jkroepke
- email: scott@r6by.com
  name: scottrigby
  url: https://github.com/scottrigby
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
  url: https://github.com/Xtigyro
- email: quentin.bisson@gmail.com
  name: QuentinBisson
  url: https://github.com/QuentinBisson
name: kube-prometheus-stack-crds
sources:
- https://github.com/prometheus-community/helm-charts
- https://github.com/prometheus-operator/kube-prometheus
# Based on chart version 77.6.0
version: 0.85.0
