apiVersion: v1
name: prometheus-adapter
version: 0.10.0
appVersion: 0.10.0
description: A Helm chart for k8s prometheus adapter
icon: icons/prometheus-logo.svg
home: https://github.com/kubernetes-sigs/prometheus-adapter
keywords:
  - hpa
  - metrics
  - prometheus
  - adapter
sources:
  - https://github.com/kubernetes/charts
  - https://github.com/kubernetes-sigs/prometheus-adapter
maintainers:
  - name: mattiasgees
    email: mattias.gees@jetstack.io
  - name: steven-sheehy
  - name: hectorj2f
    email: hfernandez@mesosphere.com
kubeVersion: '>= 1.30.0 <= 1.32.0'
