apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "core-capi.fullname" . }}-aggregated-manager-role
  labels:
    cluster.x-k8s.io/provider: cluster-api
  {{- include "core-capi.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      cluster.x-k8s.io/aggregate-to-manager: "true"
rules: []
