apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "core-capi.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "core-capi.labels" . | nindent 4 }}
spec:
  selfSigned: {}
