apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core-capi.fullname" . }}-manager
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  {{- include "core-capi.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.manager.serviceAccount.annotations | nindent 4 }}
