apiVersion: v1
appVersion: 1.22.6
description: Helm chart for deploying Istio cluster resources and CRDs
icon: icons/android-192x192.png
keywords:
- istio
name: istio-base
sources:
- https://github.com/istio/istio
version: 1.22.6
