apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "control-plane-capi.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "control-plane-capi.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "control-plane-capi.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "control-plane-capi.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "control-plane-capi.fullname" . }}-selfsigned-issuer'
  secretName: capi-kubeadm-control-plane-webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle
