apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-os-ingest
  labels:
    k8s-app: verrazzano.io
    vmo.v1.verrazzano.io: system
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: verrazzano-cluster-issuer
    cert-manager.io/common-name: opensearch.vmi.system.default.100.101.68.154.nip.io
    external-dns.alpha.kubernetes.io/target: verrazzano-ingress.default.100.101.68.154.nip.io
    external-dns.alpha.kubernetes.io/ttl: "60"
    field.cattle.io/publicEndpoints: '[{"addresses":["100.101.68.154"],"port":443,"protocol":"HTTPS","serviceName":"verrazzano-system:verrazzano-authproxy","ingressName":"verrazzano-system:vmi-system-os-ingest","hostname":"opensearch.vmi.system.default.100.101.68.154.nip.io","path":"/()(.*)","allNodes":false}]'
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 65M
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: ${service_name}.${namespace}.svc.cluster.local
spec:
  ingressClassName: verrazzano-nginx
  rules:
  - host: opensearch.vmi.system.default.100.101.68.154.nip.io
    http:
      paths:
      - backend:
          service:
            name: verrazzano-authproxy
            port:
              number: 8775
        path: /()(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - opensearch.vmi.system.default.100.101.68.154.nip.io
    secretName: system-tls-os-ingest