apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-os-ingest
  labels:
    k8s-app: verrazzano.io
    vmo.v1.verrazzano.io: system
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 65M
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: ${service_name}.${namespace}.svc.cluster.local
 {{- .Values.ingress.extraAnnotations | toYaml | nindent 4 }}
spec:
  ingressClassName: verrazzano-nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: verrazzano-authproxy
            port:
              number: 8775
        path: /()(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: system-tls-os-ingest