apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mychart.fullname" . }}-es-data
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: verrazzano-network-policies
    meta.helm.sh/release-namespace: verrazzano-system
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-master: "true"
    ports:
    - port: 9300
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-data: "true"
    ports:
    - port: 9300
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-ingest: "true"
    ports:
    - port: 9200
      protocol: TCP
    - port: 9300
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: system-osd
    ports:
    - port: 9200
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          verrazzano.io/namespace: verrazzano-monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 9200
      protocol: TCP
    - port: 15090
      protocol: TCP
  podSelector:
    matchLabels:
      opensearch.verrazzano.io/role-data: "true"
  policyTypes:
  - Ingress
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mychart.fullname" . }}-es-master
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: verrazzano-network-policies
    meta.helm.sh/release-namespace: verrazzano-system
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          k8s-app: verrazzano-monitoring-operator
    ports:
    - port: 9200
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-master: "true"
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-data: "true"
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-ingest: "true"
    ports:
    - port: 9300
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          verrazzano.io/namespace: verrazzano-monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 9200
      protocol: TCP
    - port: 15090
      protocol: TCP
  podSelector:
    matchLabels:
      opensearch.verrazzano.io/role-master: "true"
  policyTypes:
  - Ingress
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mychart.fullname" . }}-os-ingest
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: verrazzano-network-policies
    meta.helm.sh/release-namespace: verrazzano-system
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          verrazzano.io/namespace: verrazzano-system
      podSelector:
        matchLabels:
          app: verrazzano-authproxy
    ports:
    - port: 9200
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-master: "true"
    - podSelector:
        matchLabels:
          opensearch.verrazzano.io/role-data: "true"
    ports:
    - port: 9300
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: system-osd
    ports:
    - port: 9200
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          verrazzano.io/namespace: verrazzano-monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 9200
      protocol: TCP
    - port: 15090
      protocol: TCP
  podSelector:
    matchLabels:
      opensearch.verrazzano.io/role-ingest: "true"
  policyTypes:
  - Ingress
status: {}