apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-es-data
  labels:
    k8s-app: verrazzano.io
    verrazzano-component: opensearch
    vmo.v1.verrazzano.io: system
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.esData.type }}
  selector:
    opensearch.verrazzano.io/role-data: "true"
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.esData.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-es-master
  labels:
    k8s-app: verrazzano.io
    verrazzano-component: opensearch
    vmo.v1.verrazzano.io: system
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.esMaster.type }}
  selector:
    opensearch.verrazzano.io/role-master: "true"
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.esMaster.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-es-master-http
  labels:
    k8s-app: verrazzano.io
    verrazzano-component: opensearch
    vmo.v1.verrazzano.io: system
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.esMasterHttp.type }}
  selector:
    opensearch.verrazzano.io/role-master: "true"
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.esMasterHttp.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-os-ingest
  labels:
    k8s-app: verrazzano.io
    verrazzano-component: opensearch
    vmo.v1.verrazzano.io: system
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.osIngest.type }}
  selector:
    opensearch.verrazzano.io/role-ingest: "true"
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.osIngest.ports | toYaml | nindent 2 }}