apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-es-data
  labels:
  {{- .Values.esData.service.extraLabels | toYaml | nindent 4 }}
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.esData.type }}
  selector:
  {{- .Values.esData.service.extraSelectorLabels | toYaml | nindent 4 }}
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.esData.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-es-master
  labels:
  {{- .Values.esMaster.service.extraLabels | toYaml | nindent 4 }}
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.esMaster.type }}
  selector:
  {{- .Values.esMaster.service.extraSelectorLabels | toYaml | nindent 4 }}
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.esMaster.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-es-master-http
  labels:
  {{- .Values.esMasterHttp.service.extraLabels | toYaml | nindent 4 }}
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.esMasterHttp.type }}
  selector:
  {{- .Values.esMasterHttp.service.extraSelectorLabels | toYaml | nindent 4 }}
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.esMasterHttp.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-os-ingest
  labels:
  {{- .Values.osIngest.service.extraLabels | toYaml | nindent 4 }}
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.osIngest.type }}
  selector:
  {{- .Values.osIngest.service.extraSelectorLabels | toYaml | nindent 4 }}
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.osIngest.ports | toYaml | nindent 2 }}