---
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        capv.infrastucture.cluster.x-k8s.io/aggregate-to-manager: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
    clusterctl.cluster.x-k8s.io: ""
  name: capv-aggregated-manager-role
rules: []

