controllerManager:
  manager:
    args:
      - --leader-elect
      - --diagnostics-address=:8443
      - --insecure-diagnostics=false
      - --feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=false,RuntimeSDK=false,MachineSetPreflightChecks=true,MachineWaitForVolumeDetachConsiderVolumeAttachments=true,PriorityQueue=false
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsGroup: 65532
      runAsUser: 65532
    image:
      repository: olcne/cluster-api-controller
      tag: v1.10.7
    imagePullPolicy: IfNotPresent
  replicas: 1
kubernetesClusterDomain: cluster.local
manager:
  serviceAccount:
    annotations: {}
webhookService:
  ports:
    - port: 443
      targetPort: webhook-server
  type: ClusterIP
fullnameOverride: capi
