{{- if ( or .Values.configFilepath .Values.configInline ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metallb.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
{{ if .Values.configFilepath }}
data:
  config: {{- toYaml .Values.configFilepath | nindent 4 }}
{{ else }}
data:
  config: {{- toYaml .Values.configInline | nindent 4 }}
{{ end }}
{{- end }}
