{
 "title": "OpenSearch Summary Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_status{cluster=\"system\"})/count(opensearch_cluster_status{cluster=\"system\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_nodes_number{verrazzano_cluster=\"local\"})/count(opensearch_cluster_nodes_number{verrazzano_cluster=\"local\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_datanodes_number{verrazzano_cluster=\"local\"})/count(opensearch_cluster_datanodes_number{verrazzano_cluster=\"local\"})"
    }
   ]
  },
  {
   "title": "Index Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (index) (opensearch_index_replicas_number{verrazzano_cluster=\"local\"}))",
     "legendFormat": "index count"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_pending_tasks_number{verrazzano_cluster=\"local\"})/count(opensearch_cluster_pending_tasks_number{verrazzano_cluster=\"local\"})"
    }
   ]
  },
  { "title": "Shard Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=\"system\", type=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=\"system\", type=\"active_primary\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=\"system\", type=\"unassigned\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=\"system\", type=\"initializing\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_shards_number{cluster=\"system\", type=\"relocating\"})"
    }
   ]
  },
  {
   "title": "Shards Per Index",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(opensearch_index_shards_number{cluster=\"system\",type=\"active\"}) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Index Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Index Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by (index) (opensearch_index_replicas_number{cluster=\"system\"}))",
     "legendFormat": "index count"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "opensearch_indices_store_size_bytes{cluster=\"system\",job=\"vmi-system-es-data\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Indexing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_count{job=\"vmi-system-es-data\", verrazzano_cluster=\"local\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Indexing Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_time_seconds{job=\"vmi-system-es-data\", verrazzano_cluster=\"local\"}[5m])/rate(opensearch_indices_indexing_index_count{job=\"vmi-system-es-data\", verrazzano_cluster=\"local\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Document Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Documents Index Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(opensearch_index_doc_number{cluster=\"system\",job=\"vmi-system-es-data\",context=\"total\"}[1h])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(opensearch_indices_merges_total_docs_count{cluster=\"system\",job=\"vmi-system-es-data\"})",
     "legendFormat": "total documents"
    }
   ]
  },
  { "title": "Disk And JVM Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_fs_total_total_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master\"}-opensearch_fs_total_free_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Watermark %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max((1 - (opensearch_fs_path_available_bytes /opensearch_fs_path_total_bytes))* 100)",
     "legendFormat": "current_disk_watermark"
    },
    {
     "expr": "max(opensearch_cluster_routing_allocation_disk_watermark_low_pct{cluster=\"system\"})",
     "legendFormat": "disk_watermark_low_pct"
    },
    {
     "expr": "max(opensearch_cluster_routing_allocation_disk_watermark_high_pct{cluster=\"system\"})",
     "legendFormat": "disk_watermark_high_pct"
    },
    {
     "expr": "max(opensearch_cluster_routing_allocation_disk_watermark_flood_stage_pct{cluster=\"system\"})",
     "legendFormat": "disk_watermark_flood_stage_pct"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1-(opensearch_fs_total_available_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master\"}/opensearch_fs_total_total_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master\"}))*100) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Heap Memory %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((opensearch_jvm_mem_heap_used_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master|vmi-system-os-ingest\"}/opensearch_jvm_mem_heap_max_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master|vmi-system-os-ingest\"})*100) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Max Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(opensearch_jvm_mem_heap_max_bytes{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-es-master|vmi-system-os-ingest\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Avg Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(opensearch_jvm_mem_heap_used_bytes{instance=~\".*:9200\", verrazzano_cluster=\"local\",job=~\"vmi-system-es-data|vmi-system-es-master|vmi-system-os-ingest\"}[15m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Avg CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*:9100\", verrazzano_cluster=\"local\"}[5m])) by(mode) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max(rate(opensearch_indices_search_fetch_count{cluster=\"system\",job=~\"vmi-system-es-data|vmi-system-os-ingest|vmi-system-es-master\"}[1h])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(opensearch_threadpool_threads_number{verrazzano_cluster=\"local\", name!=\"management\", type=\"active\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "group by (node)(opensearch_process_file_descriptors_max_number{cluster=\"system\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(opensearch_jvm_gc_collection_time_seconds{verrazzano_cluster=\"local\",job=~\"vmi-system-es-data|vmi-system-es-master|vmi-system-os-ingest\"}[5m])) by (node,gc)",
     "legendFormat": "{{node}}:{{gc}}"
    }
   ]
  },
  { "title": "Search Rate And Search Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Search Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opensearch_indices_search_query_count{job=\"vmi-system-es-data\", verrazzano_cluster=\"local\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(opensearch_indices_search_query_time_seconds{job=\"vmi-system-es-data\", verrazzano_cluster=\"local\"}[5m])/rate(opensearch_indices_search_query_count{job=\"vmi-system-es-data\", verrazzano_cluster=\"local\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}