apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logging.name }}-es-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.logging.name }}
data:
  es-url: {{ .Values.logging.osURL }}
  es-secret: {{ .Values.logging.credentialsSecret }}