apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.logging.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}