apiVersion: v1
appVersion: 0.12.0
description: A Helm chart for k8s prometheus adapter
icon: icons/prometheus-logo.svg
home: https://github.com/kubernetes-sigs/prometheus-adapter
keywords:
- hpa
- metrics
- prometheus
- adapter
maintainers:
- email: mattias.gees@jetstack.io
  name: mattiasgees
  url: https://github.com/mattiasgees
- name: steven-sheehy
  url: https://github.com/steven-sheehy
- email: hfernandez@mesosphere.com
  name: hectorj2f
  url: https://github.com/hectorj2f
name: prometheus-adapter
sources:
- https://github.com/kubernetes/charts
- https://github.com/kubernetes-sigs/prometheus-adapter
# Original chart version 5.1.0
version: 0.12.0
kubeVersion: '>= 1.26.0 < 1.33.0'
