apiVersion: v2
name: istio-gateway
description: Helm chart for deploying Istio gateways
type: application

version: 1.22.8
appVersion: 1.22.8

sources:
- https://github.com/istio/istio
icon: icons/android-192x192.png
keywords:
- istio
- gateways
kubeVersion: '>= 1.30.0 < 1.32.0'
