apiVersion: v2
name: fluent-operator
description: Fluent Operator provides great flexibility in building a logging layer based on Fluent Bit and Fluentd.
keywords:
  - logging
  - fluent-bit
  - fluentd
  - operator
version: 3.2.0
appVersion: 3.2.0
icon: icons/fluent-operator-icon.svg
home: https://www.fluentd.org/
sources:
  - https://github.com/fluent/fluent-operator
kubeVersion: '>= 1.30.0 <= 1.32.0'
