apiVersion: v2
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: icons/prometheus-logo.svg
type: application
maintainers:
  - name: andrewgkew
    email: andrew@quadcorps.co.uk
  - name: gianrubio
    email: gianrubio@gmail.com
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
  - name: GMartinez-Sisti
    email: kube-prometheus-stack@sisti.pt
  - name: scottrigby
    email: scott@r6by.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: QuentinBisson
    email: quentin.bisson@gmail.com
name: kube-prometheus-stack
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
version: 0.63.0
appVersion: 0.63.0
kubeVersion: ">= 1.26.0 < 1.33.0"
home: https://github.com/prometheus-operator/kube-prometheus
keywords:
  - operator
  - prometheus
  - kube-prometheus
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
dependencies:
  - name: kube-state-metrics
    version: "2.8.*"
    repository: file://../kube-state-metrics-2.8.2
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "1.6.1"
    repository: file://../prometheus-node-exporter-1.6.1
    condition: nodeExporter.enabled
  - name: grafana
    version: "7.5.*"
    repository: file://../grafana-7.5.17
    condition: grafana.enabled
