apiVersion: v2
appVersion: 1.26.8
description: Helm chart for deploying Istio cluster resources and CRDs
icon: icons/android-192x192.png
keywords:
  - istio
name: istio-base
sources:
  - https://github.com/istio/istio
version: 1.26.8
kubeVersion: '>= 1.29.0 < 1.34.0'
