apiVersion: v2
appVersion: 9.2.10
description: The leading tool for querying and visualizing time series and metrics.
kubeVersion: '>= 1.26.0 < 1.33.0'
maintainers:
  - email: zanhsieh@gmail.com
    name: zanhsieh
  - email: rluckie@cisco.com
    name: rtluckie
  - email: maor.friedman@redhat.com
    name: maorfr
  - email: miroslav.hadzhiev@gmail.com
    name: Xtigyro
  - email: mail@torstenwalter.de
    name: torstenwalter
  - email: github@jkroepke.de
    name: jkroepke
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/grafana
home: https://grafana.com
keywords:
- monitoring
- metric
name: grafana
type: application
version: 9.2.10
icon: icons/grafana-icon.svg
sources:
- https://github.com/grafana/grafana
- https://github.com/grafana/helm-charts
