apiVersion: v2
name: grafana
# upstream version 6.44.11
version: 9.2.10
appVersion: 9.2.10
kubeVersion: '>= 1.26.0 < 1.33.0'
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: icons/grafana-icon.svg
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: zanhsieh
    email: zanhsieh@gmail.com
  - name: rtluckie
    email: rluckie@cisco.com
  - name: maorfr
    email: maor.friedman@redhat.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: torstenwalter
    email: mail@torstenwalter.de
type: application
