controllerManager:
  manager:
    args:
    - --leader-elect
    - --diagnostics-address=:8443
    - --insecure-diagnostics=false
    - --use-deprecated-infra-machine-naming=false
    - --feature-gates=MachinePool=true,ClusterTopology=false,KubeadmBootstrapFormatIgnition=true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsGroup: 65532
      runAsUser: 65532
    image:
      repository: olcne/kubeadm-control-plane-controller
      tag: v1.9.4
    imagePullPolicy: IfNotPresent
  replicas: 1
kubernetesClusterDomain: cluster.local
manager:
  serviceAccount:
    annotations: {}
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
proxy:
  httpsProxy:
  httpProxy:
  noProxy:
