apiVersion: v1
kind: Secret
metadata:
  name: {{ include "externalip-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: {{ .Values.caCert }}
  tls.crt: {{ .Values.tlsCert }}
  tls.key: {{ .Values.tlsKey }}
