{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: {{ .Values.caCert }}
  tls.crt: {{ .Values.tlsCert }}
  tls.key: {{ .Values.tlsKey }}
{{ end -}}
