apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
webhooks:
- clientConfig:
    caBundle: '{{ .Values.caCert }}'
    service:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      path: /validate-service
  failurePolicy: Fail
  name: validate-externalip.webhook.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: None
  admissionReviewVersions:
  - v1beta1
