annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
    - name: Upgrade Process
      url: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#upgrading-chart
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: 0.85.0
dependencies:
- condition: crds.enabled
  name: crds
  repository: ""
  version: 0.0.0
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: file://../kube-state-metrics-2.17.0
  version: 2.17.0
- condition: nodeExporter.enabled
  name: prometheus-node-exporter
  repository: file://../prometheus-node-exporter-1.9.1
  version: 1.9.1
- condition: grafana.enabled
  name: grafana
  repository: file://../grafana-9.2.10
  version: 9.2.10
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
  and Prometheus rules combined with documentation and scripts to provide easy to
  operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus
  Operator.
home: https://github.com/prometheus-operator/kube-prometheus
icon: icons/prometheus-logo.svg
keywords:
- operator
- prometheus
- kube-prometheus
kubeVersion: '>= 1.26.0 < 1.34.0'
maintainers:
- email: andrew@quadcorps.co.uk
  name: andrewgkew
  url: https://github.com/andrewgkew
- email: gianrubio@gmail.com
  name: gianrubio
  url: https://github.com/gianrubio
- email: github.gkarthiks@gmail.com
  name: gkarthiks
  url: https://github.com/gkarthiks
- email: kube-prometheus-stack@sisti.pt
  name: GMartinez-Sisti
  url: https://github.com/GMartinez-Sisti
- email: github@jkroepke.de
  name: jkroepke
  url: https://github.com/jkroepke
- email: scott@r6by.com
  name: scottrigby
  url: https://github.com/scottrigby
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
  url: https://github.com/Xtigyro
- email: quentin.bisson@gmail.com
  name: QuentinBisson
  url: https://github.com/QuentinBisson
name: kube-prometheus-stack
sources:
- https://github.com/prometheus-community/helm-charts
- https://github.com/prometheus-operator/kube-prometheus
type: application
# Based on chart version 77.6.0
version: 0.85.0
