# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "olvm-capi.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-olvm
    clusterctl.cluster.x-k8s.io: ""
    control-plane: operator
  {{- include "olvm-capi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-olvm
      control-plane: operator
    {{- include "olvm-capi.selectorLabels" . | nindent 6 }}
  {{- with .Values.operator.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-olvm
        control-plane: operator
      {{- include "olvm-capi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: operator
        args: {{- toYaml .Values.operator.container.args | nindent 8 }}
        command:
        - /olvm-capi-operator
        env:
        {{ if .Values.proxy.httpsProxy }}
        - name: https_proxy
          value: {{ quote .Values.proxy.httpsProxy }}
        {{ end }}
        {{ if .Values.proxy.httpProxy }}
        - name: http_proxy
          value: {{ quote .Values.proxy.httpProxy }}
        {{ end }}
        {{ if .Values.proxy.noProxy }}
        - name: no_proxy
          value: {{ quote .Values.proxy.noProxy }}
        {{ end }}
        image: {{ .Values.operator.container.image.repository}}:{{ .Values.operator.container.image.tag }}
        imagePullPolicy: {{ .Values.operator.container.imagePullPolicy }}
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: healthz
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        - containerPort: {{ .Values.metricsPort }}
          name: metrics
          protocol: TCP
#        readinessProbe:
#          httpGet:
#            path: /readyz
#            port: healthz
        resources:
          {{- toYaml .Values.operator.container.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.operator.container.containerSecurityContext | nindent 12 }}
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "olvm-capi.fullname" . }}-operator
      terminationGracePeriodSeconds: 0
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
