# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "olvm-capi.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-olvm
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  {{- include "olvm-capi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-olvm
      control-plane: controller-manager
    {{- include "olvm-capi.selectorLabels" . | nindent 6 }}
  {{- with .Values.controllerManager.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-olvm
        control-plane: controller-manager
      {{- include "olvm-capi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: manager
          args:
            - --zap-log-level={{ .Values.logLevel }}
          image: {{ .Values.controllerManager.manager.image.repository}}:{{ .Values.controllerManager.manager.image.tag }}
          imagePullPolicy: {{ .Values.controllerManager.manager.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
            - containerPort: {{ .Values.metricsPort }}
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
            {{- toYaml .Values.controllerManager.manager.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controllerManager.manager.containerSecurityContext | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        {{- toYaml .Values.controllerManager.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "olvm-capi.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
