# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "olvm-capi.fullname" . }}-metrics-reader
  labels:
    cluster.x-k8s.io/provider: infrastructure-olvm
    clusterctl.cluster.x-k8s.io: ""
  {{- include "olvm-capi.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get