# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olvm-capi.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-olvm
    clusterctl.cluster.x-k8s.io: ""
  {{- include "olvm-capi.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}
