# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "olvm-capi.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "olvm-capi.fullname" . }}-serving-cert
  labels:
  {{- include "olvm-capi.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1alpha1
  clientConfig:
    service:
      name: '{{ include "olvm-capi.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-olvmcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.olvmcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - olvmclusters
  sideEffects: None
- admissionReviewVersions:
  - v1alpha1
  clientConfig:
    service:
      name: '{{ include "olvm-capi.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-olvmmachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.olvmmachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - olvmmachinetemplates
  sideEffects: None
