apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oci-capi.fullname" . }}-trusted-certs
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-oci
    clusterctl.cluster.x-k8s.io: ""
  {{- include "oci-capi.labels" . | nindent 4 }}
data:
  custom-certs.pem: {{ .Values.managerConfig.controllerManagerConfigYaml
    | toYaml | indent 1 }}