{{- if .Values.createKubevirt }}
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml $.Values.kubevirt | nindent 2 }}
{{end}}
