apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.csiNode.ovirtNode.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: plugin
    app.kubernetes.io/part-of: csi-driver-ovirt
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: plugin
      app.kubernetes.io/instance:  ovirt-csi-driver-node
      app.kubernetes.io/name: ovirt-csi-driver-node
      app.kubernetes.io/part-of: ovirt-csi-driver
    {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plugin
        app.kubernetes.io/instance:  ovirt-csi-driver-node
        app.kubernetes.io/name: ovirt-csi-driver-node
        app.kubernetes.io/part-of: ovirt-csi-driver
      {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --node-name=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi-socket/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OVIRT_CONFIG
          value: {{ quote .Values.csiNode.ovirtNode.env.ovirtConfig }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.csiNode.ovirtNode.image.repository }}:{{ .Values.csiNode.ovirtNode.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.csiNode.ovirtNode.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 3
        name: ovirt
        ports:
        - containerPort: 9898
          name: healthz
          protocol: TCP
        resources: {{- toYaml .Values.csiNode.ovirtNode.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.csiNode.ovirtNode.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /csi-socket
          name: socket-dir
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /dev
          name: dev-dir
        - mountPath: /tmp/config
          name: config
      - args:
        - --csi-address=/csi-socket/csi.sock
        - --health-port=9898
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.csiNode.livenessProbe.image.repository }}:{{ .Values.csiNode.livenessProbe.image.tag
          | default .Chart.AppVersion }}
        name: liveness-probe
        resources: {{- toYaml .Values.csiNode.livenessProbe.resources | nindent
          10 }}
        volumeMounts:
        - mountPath: /csi-socket
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=/csi-socket/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.ovirt.org/csi.sock
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.csiNode.csiDriverRegistrar.image.repository }}:{{
          .Values.csiNode.csiDriverRegistrar.image.tag | default .Chart.AppVersion
          }}
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.ovirt.org/csi.sock
            - --mode=kubelet-registration-probe
          initialDelaySeconds: 30
          timeoutSeconds: 15
        name: csi-driver-registrar
        resources: {{- toYaml .Values.csiNode.csiDriverRegistrar.resources |
          nindent 10 }}
        volumeMounts:
        - mountPath: /csi-socket
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |
          #!/bin/sh
          cat << EOF > /tmp/config/ovirt-config.yaml
          ovirt_url: $OVIRT_URL
          ovirt_username: $OVIRT_USERNAME
          ovirt_password: $OVIRT_PASSWORD
          # set a valid path only if ca bundle has content
          ovirt_cafile: ${OVIRT_CA_BUNDLE:+$OVIRT_CAFILE}
          ovirt_insecure: {{ .Values.ovirt.insecure }}
          EOF
          if [[ -n "$OVIRT_CA_BUNDLE" ]]; then echo "$OVIRT_CA_BUNDLE" > $OVIRT_CAFILE ; fi
        env:
        - name: OVIRT_URL
          valueFrom:
            secretKeyRef:
              key: ovirt_url
              name: {{ .Values.ovirt.secretName }}
        - name: OVIRT_USERNAME
          valueFrom:
            secretKeyRef:
              key: ovirt_username
              name: {{ .Values.ovirt.secretName }}
        - name: OVIRT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ovirt_password
              name: {{ .Values.ovirt.secretName }}
{{ if .Values.ovirt.caProvided }}
        - name: OVIRT_CAFILE
          value: {{ quote .Values.csiNode.prepareOvirtConfig.env.ovirtCafile
            }}
        - name: OVIRT_CA_BUNDLE
          valueFrom:
            configMapKeyRef:
              key: ca.crt
              name: {{ .Values.ovirt.caConfigMapName }}
{{ end }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.csiNode.prepareOvirtConfig.image.repository }}:{{
          .Values.csiNode.prepareOvirtConfig.image.tag | default .Chart.AppVersion
          }}
        imagePullPolicy: {{ .Values.csiNode.prepareOvirtConfig.imagePullPolicy
          }}
        name: prepare-ovirt-config
        resources: {{- toYaml .Values.csiNode.prepareOvirtConfig.resources |
          nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/config
          name: config
      serviceAccountName: {{ include "mychart.fullname" . }}-node-sa
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/csi.ovirt.org
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet
          type: DirectoryOrCreate
        name: kubelet-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
      - emptyDir:
          medium: Memory
        name: config