apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/part-of: csi-driver-ovirt
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  attachRequired: true
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent