controller:
  kind: DaemonSet
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
  service:
    type: ClusterIP
  extraModules:
    - name: opentelemetry
      image:
        registry: os
        image: oraclelinux
        tag: 8-slim
