controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
  extraModules:
    - name: opentelemetry
      image:
        registry: os
        image: oraclelinux
        tag: 8-slim
      containerSecurityContext:
        allowPrivilegeEscalation: false
