global:
  oci:
    registry: "ghcr.io/oracle"
  csi:
    registry: "olcne"
  compact: false
  namespace: kube-system

oci:
  useinstanceprincipals: false
  privatekey: ""

volumeProvisionerConfig: oci-volume-provisioner
cloudControllerManagerConfig: oci-cloud-controller-manager

cloud-provider-oci: "v1.30.0"

csi-provisioner: "v3.5.0"

csi-attacher: "v4.3.0"

csi-resizer: "v1.8.0"

csi-node-driver-registrar: "v2.8.0"

csi-snapshotter: "v6.2.2"
