apiVersion: v2
appVersion: 1.28.10
description: Helm chart for istio-cni components
icon: icons/android-192x192.png
keywords:
  - istio-cni
  - istio
name: istio-cni
sources:
  - https://github.com/istio/istio
version: 1.28.10
kubeVersion: '>= 1.30.0 < 1.35.0'
