apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.fullname" . }}-ovirt-csi-driver-controller-sa
  labels:
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: csi-driver-ovirt
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ovirtCsiDriverControllerSa.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.fullname" . }}-ovirt-csi-driver-node-sa
  labels:
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: csi-driver-ovirt
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ovirtCsiDriverNodeSa.serviceAccount.annotations | nindent 4 }}