{{- $files := .Files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-services-grafana-dashboards
  namespace: istio-system
data:
{{- range $path, $bytes := .Files.Glob "dashboards/istio-services/*.json" }}
#{{- $filename := trimSuffix (ext $path) (base $path) }}
#{{ $filename | indent 2 }}: |
{{ (base $path) | indent 2 }}: |
{{ $files.Get $path | indent 4}}'
{{- end }}
