apiVersion: v1
kind: Service
metadata:
  name: {{ include "capv.fullname" . }}-metrics
  labels:
    {{- include "capv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    {{- range .Values.metricsService.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "capv.selectorLabels" . | nindent 4 }}