apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capv.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "capv.labels" . | nindent 4 }}
webhooks: []