apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capv.fullname" . }}
  labels:
    {{- include "capv.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}