apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "capv.fullname" . }}-serving-cert
  labels:
    {{- include "capv.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "capv.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "capv.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "capv.fullname" . }}-selfsigned-issuer
  secretName: {{ include "capv.fullname" . }}-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "capv.fullname" . }}-selfsigned-issuer
  labels:
    {{- include "capv.labels" . | nindent 4 }}
spec:
  selfSigned: {}